import React from "react";
import { motion } from "motion/react";
import Button from "./Button";
const Hero = () => {
  const parent = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: {
        staggerChildren: 0.2, // delay between children
        delayChildren: 0.2, // delay before first child
      },
    },
  };

  const child = {
    hidden: { opacity: 0, y: 20, filter: "blur(4px)" },
    show: {
      opacity: 1,
      y: 0,
      filter: "blur(0px)",
      transition: { duration: 0.5, ease: "easeOut" },
    },
  };
  return (
    <motion.div
      variants={parent}
      initial="hidden"
      animate="show"
      className="max-w-6xl flex justify-between px-8  pt-26 md:pt-48 md:mx-28 h-screen "
    >
      <motion.div variants={child} className="heading space-y-2 z-20 tracking-tighter">
        <motion.h1 variants={child} className="text-4xl md:flex md:gap-1 md:items-center font-oswald-100 uppercase  font-bold  md:font-semibold  leading-12">
          Cook Any <span></span>
          <motion.span
            initial={{ opacity: 0, filter: "blur(7px)", y: 20 }}
            animate={{ opacity: 1, y: 0, filter: "blur(0px)", skewX: -4 }}
            transition={{ duration: 0.8, ease: "easeInOut" }}
            className="md:p-1 md:rounded-md md:text-neutral-100 md:bg-amber-300 md:inline-block "
          >
            dish
          </motion.span>{" "}
          with Just a Name.
        </motion.h1>
        <motion.h3 variants={child} className="text-md  capitalize ">
          Type any dish name, number of servings, and optional notes — and get a
          full,
          <br className="hidden md:flex" /> step-by-step recipe instantly
          generated by AI.
        </motion.h3>
        <Button variants={child} className="capitalize mt-4 font-bold ">
          Generate Your First Recipe Now{" "}
        </Button>
      </motion.div>
    </motion.div>
  );
};

export default Hero;
